@api = http://localhost:3000/users
@log = http://localhost:3000/register

GET {{api}}

###

POST {{api}}

Content-Type: application/json 
  {
  "dni": "12345",
  "email": "asd@asdd.com",
  "nombre": "Simon",
  "apellido": "Apeli",
  "user_password": "12334"
}

###

POST {{log}}
Content-Type: application/json

{
  "dni": "78910098",
  "email": "ejemplo@correo.com",
  "nombre": "Juan",
  "apellido": "Perez",
  "user_password": "contrasena"
}

